using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace VideoLibrary.Data.Migrations
{
    /// <inheritdoc />
    public partial class LanguageCountry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "CountryId",
                table: "Movies",
                type: "nvarchar(2)",
                maxLength: 2,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "LanguageId",
                table: "Movies",
                type: "nvarchar(3)",
                maxLength: 3,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Tagline",
                table: "Movies",
                type: "nvarchar(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "LookupCountries",
                columns: table => new
                {
                    CountryId = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Order = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LookupCountries", x => x.CountryId);
                });

            migrationBuilder.CreateTable(
                name: "LookupLanguages",
                columns: table => new
                {
                    LanguageId = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Order = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LookupLanguages", x => x.LanguageId);
                });

            migrationBuilder.InsertData(
                table: "LookupCountries",
                columns: new[] { "CountryId", "Name", "Order" },
                values: new object[,]
                {
                    { "AD", "Andorra", 2 },
                    { "AE", "United Arab Emirates", 2 },
                    { "AF", "Afghanistan", 2 },
                    { "AG", "Antigua and Barbuda", 2 },
                    { "AL", "Albania", 2 },
                    { "AM", "Armenia", 2 },
                    { "AO", "Angola", 2 },
                    { "AR", "Argentina", 2 },
                    { "AS", "American Samoa", 2 },
                    { "AT", "Austria", 2 },
                    { "AU", "Australia", 2 },
                    { "AZ", "Azerbaijan", 2 },
                    { "BA", "Bosnia and Herzegovina", 2 },
                    { "BB", "Barbados", 2 },
                    { "BD", "Bangladesh", 2 },
                    { "BE", "Belgium", 2 },
                    { "BF", "Burkina Faso", 2 },
                    { "BG", "Bulgaria", 2 },
                    { "BH", "Bahrain", 2 },
                    { "BI", "Burundi", 2 },
                    { "BJ", "Benin", 2 },
                    { "BN", "Brunei", 2 },
                    { "BO", "Bolivia", 2 },
                    { "BR", "Brazil", 2 },
                    { "BS", "Bahamas", 2 },
                    { "BT", "Bhutan", 2 },
                    { "BW", "Botswana", 2 },
                    { "BY", "Belarus", 2 },
                    { "BZ", "Belize", 2 },
                    { "CA", "Canada", 0 },
                    { "CD", "Congo (Kinshasa)", 2 },
                    { "CF", "Central African Republic", 2 },
                    { "CG", "Congo (Brazzaville)", 2 },
                    { "CH", "Switzerland", 2 },
                    { "CL", "Chile", 2 },
                    { "CM", "Cameroon", 2 },
                    { "CN", "China", 2 },
                    { "CO", "Colombia", 2 },
                    { "CR", "Costa Rica", 2 },
                    { "CU", "Cuba", 2 },
                    { "CV", "Cape Verde", 2 },
                    { "CY", "Cyprus", 2 },
                    { "CZ", "Czech Republic", 2 },
                    { "DE", "Germany", 2 },
                    { "DJ", "Djibouti", 2 },
                    { "DK", "Denmark", 2 },
                    { "DM", "Dominica", 2 },
                    { "DO", "Dominican Republic", 2 },
                    { "DZ", "Algeria", 2 },
                    { "EC", "Ecuador", 2 },
                    { "EE", "Estonia", 2 },
                    { "EG", "Egypt", 2 },
                    { "ER", "Eritrea", 2 },
                    { "ES", "Spain", 2 },
                    { "ET", "Ethiopia", 2 },
                    { "FI", "Finland", 2 },
                    { "FJ", "Fiji", 2 },
                    { "FM", "Micronesia", 2 },
                    { "FR", "France", 2 },
                    { "GA", "Gabon", 2 },
                    { "GB", "United Kingdom", 2 },
                    { "GD", "Grenada", 2 },
                    { "GE", "Georgia", 2 },
                    { "GH", "Ghana", 2 },
                    { "GM", "Gambia", 2 },
                    { "GN", "Guinea", 2 },
                    { "GQ", "Equatorial Guinea", 2 },
                    { "GR", "Greece", 2 },
                    { "GT", "Guatemala", 2 },
                    { "GW", "Guinea-Bissau", 2 },
                    { "GY", "Guyana", 2 },
                    { "HN", "Honduras", 2 },
                    { "HR", "Croatia", 2 },
                    { "HT", "Haiti", 2 },
                    { "HU", "Hungary", 2 },
                    { "ID", "Indonesia", 2 },
                    { "IE", "Ireland", 2 },
                    { "IL", "Israel", 2 },
                    { "IN", "India", 2 },
                    { "IQ", "Iraq", 2 },
                    { "IR", "Iran", 2 },
                    { "IS", "Iceland", 2 },
                    { "IT", "Italy", 2 },
                    { "JM", "Jamaica", 2 },
                    { "JO", "Jordan", 2 },
                    { "JP", "Japan", 2 },
                    { "KE", "Kenya", 2 },
                    { "KG", "Kyrgyzstan", 2 },
                    { "KH", "Cambodia", 2 },
                    { "KI", "Kiribati", 2 },
                    { "KM", "Comoros", 2 },
                    { "KN", "Saint Kitts and Nevis", 2 },
                    { "KR", "South Korea", 2 },
                    { "KW", "Kuwait", 2 },
                    { "KZ", "Kazakhstan", 2 },
                    { "LA", "Laos", 2 },
                    { "LB", "Lebanon", 2 },
                    { "LC", "Saint Lucia", 2 },
                    { "LI", "Liechtenstein", 2 },
                    { "LK", "Sri Lanka", 2 },
                    { "LR", "Liberia", 2 },
                    { "LS", "Lesotho", 2 },
                    { "LT", "Lithuania", 2 },
                    { "LU", "Luxembourg", 2 },
                    { "LV", "Latvia", 2 },
                    { "LY", "Libya", 2 },
                    { "MA", "Morocco", 2 },
                    { "MC", "Monaco", 2 },
                    { "MD", "Moldova", 2 },
                    { "ME", "Montenegro", 2 },
                    { "MG", "Madagascar", 2 },
                    { "MH", "Marshall Islands", 2 },
                    { "ML", "Mali", 2 },
                    { "MM", "Myanmar (Burma)", 2 },
                    { "MN", "Mongolia", 2 },
                    { "MR", "Mauritania", 2 },
                    { "MT", "Malta", 2 },
                    { "MU", "Mauritius", 2 },
                    { "MV", "Maldives", 2 },
                    { "MW", "Malawi", 2 },
                    { "MX", "Mexico", 2 },
                    { "MY", "Malaysia", 2 },
                    { "MZ", "Mozambique", 2 },
                    { "NA", "Namibia", 2 },
                    { "NE", "Niger", 2 },
                    { "NG", "Nigeria", 2 },
                    { "NI", "Nicaragua", 2 },
                    { "NL", "Netherlands", 2 },
                    { "NO", "Norway", 2 },
                    { "NP", "Nepal", 2 },
                    { "NR", "Nauru", 2 },
                    { "NZ", "New Zealand", 2 },
                    { "OM", "Oman", 2 },
                    { "PA", "Panama", 2 },
                    { "PE", "Peru", 2 },
                    { "PG", "Papua New Guinea", 2 },
                    { "PH", "Philippines", 2 },
                    { "PK", "Pakistan", 2 },
                    { "PL", "Poland", 2 },
                    { "PS", "Palestine", 2 },
                    { "PT", "Portugal", 2 },
                    { "PW", "Palau", 2 },
                    { "PY", "Paraguay", 2 },
                    { "QA", "Qatar", 2 },
                    { "RO", "Romania", 2 },
                    { "RS", "Serbia", 2 },
                    { "RU", "Russia", 2 },
                    { "RW", "Rwanda", 2 },
                    { "SA", "Saudi Arabia", 2 },
                    { "SB", "Solomon Islands", 2 },
                    { "SC", "Seychelles", 2 },
                    { "SD", "Sudan", 2 },
                    { "SE", "Sweden", 2 },
                    { "SG", "Singapore", 2 },
                    { "SI", "Slovenia", 2 },
                    { "SK", "Slovakia", 2 },
                    { "SL", "Sierra Leone", 2 },
                    { "SM", "San Marino", 2 },
                    { "SN", "Senegal", 2 },
                    { "SO", "Somalia", 2 },
                    { "SR", "Suriname", 2 },
                    { "SS", "South Sudan", 2 },
                    { "ST", "São Tomé and Príncipe", 2 },
                    { "SV", "El Salvador", 2 },
                    { "SY", "Syria", 2 },
                    { "SZ", "Swaziland (Eswatini)", 2 },
                    { "TD", "Chad", 2 },
                    { "TG", "Togo", 2 },
                    { "TH", "Thailand", 2 },
                    { "TJ", "Tajikistan", 2 },
                    { "TL", "Timor-Leste", 2 },
                    { "TM", "Turkmenistan", 2 },
                    { "TN", "Tunisia", 2 },
                    { "TO", "Tonga", 2 },
                    { "TR", "Turkey", 2 },
                    { "TT", "Trinidad and Tobago", 2 },
                    { "TV", "Tuvalu", 2 },
                    { "TW", "Taiwan", 2 },
                    { "TZ", "Tanzania", 2 },
                    { "UA", "Ukraine", 2 },
                    { "UG", "Uganda", 2 },
                    { "US", "United States", 1 },
                    { "UY", "Uruguay", 2 },
                    { "UZ", "Uzbekistan", 2 },
                    { "VC", "Saint Vincent and Grenadines", 2 },
                    { "VE", "Venezuela", 2 },
                    { "VN", "Vietnam", 2 },
                    { "VU", "Vanuatu", 2 },
                    { "WS", "Samoa", 2 },
                    { "YE", "Yemen", 2 },
                    { "ZA", "South Africa", 2 },
                    { "ZM", "Zambia", 2 },
                    { "ZW", "Zimbabwe", 2 }
                });

            migrationBuilder.InsertData(
                table: "LookupLanguages",
                columns: new[] { "LanguageId", "Name", "Order" },
                values: new object[,]
                {
                    { "aa", "Afar", 2 },
                    { "ab", "Abkhaz", 2 },
                    { "ae", "Avestan", 2 },
                    { "af", "Afrikaans", 2 },
                    { "ak", "Akan", 2 },
                    { "am", "Amharic", 2 },
                    { "an", "Aragonese", 2 },
                    { "ar", "Arabic", 2 },
                    { "as", "Assamese", 2 },
                    { "av", "Avaric", 2 },
                    { "ay", "Aymara", 2 },
                    { "az", "Azerbaijani", 2 },
                    { "ba", "Bashkir", 2 },
                    { "be", "Belarusian", 2 },
                    { "bg", "Bulgarian", 2 },
                    { "bh", "Bihari", 2 },
                    { "bi", "Bislama", 2 },
                    { "bm", "Bambara", 2 },
                    { "bn", "Bengali", 2 },
                    { "bo", "Tibetan", 2 },
                    { "br", "Breton", 2 },
                    { "bs", "Bosnian", 2 },
                    { "ca", "Catalan", 2 },
                    { "ce", "Chechen", 2 },
                    { "ch", "Chamorro", 2 },
                    { "co", "Corsican", 2 },
                    { "cr", "Cree", 2 },
                    { "cs", "Czech", 2 },
                    { "cu", "Old Church Slavonic", 2 },
                    { "cv", "Chuvash", 2 },
                    { "cy", "Welsh", 2 },
                    { "da", "Danish", 2 },
                    { "de", "German", 2 },
                    { "dv", "Divehi", 2 },
                    { "dz", "Dzongkha", 2 },
                    { "ee", "Ewe", 2 },
                    { "el", "Greek", 2 },
                    { "en", "English", 0 },
                    { "eo", "Esperanto", 2 },
                    { "es", "Spanish", 2 },
                    { "et", "Estonian", 2 },
                    { "eu", "Basque", 2 },
                    { "fa", "Persian", 2 },
                    { "ff", "Fulah", 2 },
                    { "fi", "Finnish", 2 },
                    { "fj", "Fijian", 2 },
                    { "fo", "Faroese", 2 },
                    { "fr", "French", 2 },
                    { "ga", "Irish", 2 },
                    { "gd", "Scottish Gaelic", 2 },
                    { "gl", "Galician", 2 },
                    { "gn", "Guaraní", 2 },
                    { "gu", "Gujarati", 2 },
                    { "gv", "Manx", 2 },
                    { "ha", "Hausa", 2 },
                    { "he", "Hebrew", 2 },
                    { "hi", "Hindi", 2 },
                    { "ho", "Hiri Motu", 2 },
                    { "hr", "Croatian", 2 },
                    { "ht", "Haitian", 2 },
                    { "hu", "Hungarian", 2 },
                    { "hy", "Armenian", 2 },
                    { "hz", "Herero", 2 },
                    { "ia", "Interlingua", 2 },
                    { "id", "Indonesian", 2 },
                    { "ie", "Interlingue", 2 },
                    { "ig", "Igbo", 2 },
                    { "ii", "Nuosu", 2 },
                    { "ik", "Inupiaq", 2 },
                    { "is", "Icelandic", 2 },
                    { "it", "Italian", 2 },
                    { "iu", "Inuktitut", 2 },
                    { "ja", "Japanese", 2 },
                    { "jv", "Javanese", 2 },
                    { "ka", "Georgian", 2 },
                    { "kg", "Kongo", 2 },
                    { "ki", "Kikuyu", 2 },
                    { "kj", "Kwanyama", 2 },
                    { "kk", "Kazakh", 2 },
                    { "kl", "Kalaallisut", 2 },
                    { "km", "Khmer", 2 },
                    { "kn", "Kannada", 2 },
                    { "ko", "Korean", 2 },
                    { "kr", "Kanuri", 2 },
                    { "ks", "Kashmiri", 2 },
                    { "ku", "Kurdish", 2 },
                    { "kv", "Komi", 2 },
                    { "kw", "Cornish", 2 },
                    { "ky", "Kyrgyz", 2 },
                    { "la", "Latin", 2 },
                    { "lb", "Luxembourgish", 2 },
                    { "lg", "Luganda", 2 },
                    { "li", "Limburgish", 2 },
                    { "ln", "Lingala", 2 },
                    { "lo", "Lao", 2 },
                    { "lt", "Lithuanian", 2 },
                    { "lu", "Luba-Katanga", 2 },
                    { "lv", "Latvian", 2 },
                    { "mg", "Malagasy", 2 },
                    { "mh", "Marshallese", 2 },
                    { "mi", "Māori", 2 },
                    { "mk", "Macedonian", 2 },
                    { "ml", "Malayalam", 2 },
                    { "mn", "Mongolian", 2 },
                    { "mr", "Marathi", 2 },
                    { "ms", "Malay", 2 },
                    { "mt", "Maltese", 2 },
                    { "my", "Burmese", 2 },
                    { "na", "Nauru", 2 },
                    { "nb", "Norwegian Bokmål", 2 },
                    { "nd", "North Ndebele", 2 },
                    { "ne", "Nepali", 2 },
                    { "ng", "Ndonga", 2 },
                    { "nl", "Dutch", 2 },
                    { "nn", "Norwegian Nynorsk", 2 },
                    { "no", "Norwegian", 2 },
                    { "nr", "South Ndebele", 2 },
                    { "nv", "Navajo", 2 },
                    { "ny", "Chichewa", 2 },
                    { "oc", "Occitan", 2 },
                    { "oj", "Ojibwe", 2 },
                    { "om", "Oromo", 2 },
                    { "or", "Oriya", 2 },
                    { "os", "Ossetian", 2 },
                    { "pa", "Punjabi", 2 },
                    { "pi", "Pāli", 2 },
                    { "pl", "Polish", 2 },
                    { "ps", "Pashto", 2 },
                    { "pt", "Portuguese", 2 },
                    { "qu", "Quechua", 2 },
                    { "rm", "Romansh", 2 },
                    { "rn", "Kirundi", 2 },
                    { "ro", "Romanian", 2 },
                    { "ru", "Russian", 2 },
                    { "rw", "Kinyarwanda", 2 },
                    { "sa", "Sanskrit", 2 },
                    { "sc", "Sardinian", 2 },
                    { "sd", "Sindhi", 2 },
                    { "se", "Northern Sami", 2 },
                    { "sg", "Sango", 2 },
                    { "si", "Sinhala", 2 },
                    { "sk", "Slovak", 2 },
                    { "sl", "Slovene", 2 },
                    { "sm", "Samoan", 2 },
                    { "sn", "Shona", 2 },
                    { "so", "Somali", 2 },
                    { "sq", "Albanian", 2 },
                    { "sr", "Serbian", 2 },
                    { "ss", "Swati", 2 },
                    { "st", "Southern Sotho", 2 },
                    { "su", "Sundanese", 2 },
                    { "sv", "Swedish", 2 },
                    { "sw", "Swahili", 2 },
                    { "ta", "Tamil", 2 },
                    { "te", "Telugu", 2 },
                    { "tg", "Tajik", 2 },
                    { "th", "Thai", 2 },
                    { "ti", "Tigrinya", 2 },
                    { "tk", "Turkmen", 2 },
                    { "tl", "Tagalog", 2 },
                    { "tn", "Tswana", 2 },
                    { "to", "Tonga", 2 },
                    { "tr", "Turkish", 2 },
                    { "ts", "Tsonga", 2 },
                    { "tt", "Tatar", 2 },
                    { "tw", "Twi", 2 },
                    { "ty", "Tahitian", 2 },
                    { "ug", "Uyghur", 2 },
                    { "uk", "Ukrainian", 2 },
                    { "ur", "Urdu", 2 },
                    { "uz", "Uzbek", 2 },
                    { "ve", "Venda", 2 },
                    { "vi", "Vietnamese", 2 },
                    { "vo", "Volapük", 2 },
                    { "wa", "Walloon", 2 },
                    { "wo", "Wolof", 2 },
                    { "xh", "Xhosa", 2 },
                    { "yi", "Yiddish", 2 },
                    { "yo", "Yoruba", 2 },
                    { "za", "Zhuang", 2 },
                    { "zh", "Chinese", 2 },
                    { "zu", "Zulu", 2 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Movies_CountryId",
                table: "Movies",
                column: "CountryId");

            migrationBuilder.CreateIndex(
                name: "IX_Movies_LanguageId",
                table: "Movies",
                column: "LanguageId");

            migrationBuilder.AddForeignKey(
                name: "FK_Movies_LookupCountries_CountryId",
                table: "Movies",
                column: "CountryId",
                principalTable: "LookupCountries",
                principalColumn: "CountryId");

            migrationBuilder.AddForeignKey(
                name: "FK_Movies_LookupLanguages_LanguageId",
                table: "Movies",
                column: "LanguageId",
                principalTable: "LookupLanguages",
                principalColumn: "LanguageId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Movies_LookupCountries_CountryId",
                table: "Movies");

            migrationBuilder.DropForeignKey(
                name: "FK_Movies_LookupLanguages_LanguageId",
                table: "Movies");

            migrationBuilder.DropTable(
                name: "LookupCountries");

            migrationBuilder.DropTable(
                name: "LookupLanguages");

            migrationBuilder.DropIndex(
                name: "IX_Movies_CountryId",
                table: "Movies");

            migrationBuilder.DropIndex(
                name: "IX_Movies_LanguageId",
                table: "Movies");

            migrationBuilder.DropColumn(
                name: "CountryId",
                table: "Movies");

            migrationBuilder.DropColumn(
                name: "LanguageId",
                table: "Movies");

            migrationBuilder.DropColumn(
                name: "Tagline",
                table: "Movies");
        }
    }
}
