
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VideoLibrary.Data.DbModels;

namespace VideoLibrary.Data.Configuration
{
    internal class LookupLanguageConfiguration : IEntityTypeConfiguration<LookupLanguage>
    {
        public void Configure(EntityTypeBuilder<LookupLanguage> builder)
        {

            builder.ToTable("LookupLanguages");

            builder.HasKey(e => e.LanguageId);

            builder.Property(e => e.LanguageId).IsRequired().HasMaxLength(3);
            builder.Property(e => e.Name).IsRequired().HasMaxLength(20);

            builder.HasData(
                new LookupLanguage { LanguageId = "ab", Name = "Abkhaz", Order = 2 },
                new LookupLanguage { LanguageId = "aa", Name = "Afar", Order = 2 },
                new LookupLanguage { LanguageId = "af", Name = "Afrikaans", Order = 2 },
                new LookupLanguage { LanguageId = "ak", Name = "Akan", Order = 2 },
                new LookupLanguage { LanguageId = "sq", Name = "Albanian", Order = 2 },
                new LookupLanguage { LanguageId = "am", Name = "Amharic", Order = 2 },
                new LookupLanguage { LanguageId = "ar", Name = "Arabic", Order = 2 },
                new LookupLanguage { LanguageId = "an", Name = "Aragonese", Order = 2 },
                new LookupLanguage { LanguageId = "hy", Name = "Armenian", Order = 2 },
                new LookupLanguage { LanguageId = "as", Name = "Assamese", Order = 2 },
                new LookupLanguage { LanguageId = "av", Name = "Avaric", Order = 2 },
                new LookupLanguage { LanguageId = "ae", Name = "Avestan", Order = 2 },
                new LookupLanguage { LanguageId = "ay", Name = "Aymara", Order = 2 },
                new LookupLanguage { LanguageId = "az", Name = "Azerbaijani", Order = 2 },
                new LookupLanguage { LanguageId = "bm", Name = "Bambara", Order = 2 },
                new LookupLanguage { LanguageId = "ba", Name = "Bashkir", Order = 2 },
                new LookupLanguage { LanguageId = "eu", Name = "Basque", Order = 2 },
                new LookupLanguage { LanguageId = "be", Name = "Belarusian", Order = 2 },
                new LookupLanguage { LanguageId = "bn", Name = "Bengali", Order = 2 },
                new LookupLanguage { LanguageId = "bh", Name = "Bihari", Order = 2 },
                new LookupLanguage { LanguageId = "bi", Name = "Bislama", Order = 2 },
                new LookupLanguage { LanguageId = "bs", Name = "Bosnian", Order = 2 },
                new LookupLanguage { LanguageId = "br", Name = "Breton", Order = 2 },
                new LookupLanguage { LanguageId = "bg", Name = "Bulgarian", Order = 2 },
                new LookupLanguage { LanguageId = "my", Name = "Burmese", Order = 2 },
                new LookupLanguage { LanguageId = "ca", Name = "Catalan", Order = 2 },
                new LookupLanguage { LanguageId = "ch", Name = "Chamorro", Order = 2 },
                new LookupLanguage { LanguageId = "ce", Name = "Chechen", Order = 2 },
                new LookupLanguage { LanguageId = "ny", Name = "Chichewa", Order = 2 },
                new LookupLanguage { LanguageId = "zh", Name = "Chinese", Order = 2 },
                new LookupLanguage { LanguageId = "cv", Name = "Chuvash", Order = 2 },
                new LookupLanguage { LanguageId = "kw", Name = "Cornish", Order = 2 },
                new LookupLanguage { LanguageId = "co", Name = "Corsican", Order = 2 },
                new LookupLanguage { LanguageId = "cr", Name = "Cree", Order = 2 },
                new LookupLanguage { LanguageId = "hr", Name = "Croatian", Order = 2 },
                new LookupLanguage { LanguageId = "cs", Name = "Czech", Order = 2 },
                new LookupLanguage { LanguageId = "da", Name = "Danish", Order = 2 },
                new LookupLanguage { LanguageId = "dv", Name = "Divehi", Order = 2 },
                new LookupLanguage { LanguageId = "nl", Name = "Dutch", Order = 2 },
                new LookupLanguage { LanguageId = "dz", Name = "Dzongkha", Order = 2 },
                new LookupLanguage { LanguageId = "en", Name = "English", Order = 0 },
                new LookupLanguage { LanguageId = "eo", Name = "Esperanto", Order = 2 },
                new LookupLanguage { LanguageId = "et", Name = "Estonian", Order = 2 },
                new LookupLanguage { LanguageId = "ee", Name = "Ewe", Order = 2 },
                new LookupLanguage { LanguageId = "fo", Name = "Faroese", Order = 2 },
                new LookupLanguage { LanguageId = "fj", Name = "Fijian", Order = 2 },
                new LookupLanguage { LanguageId = "fi", Name = "Finnish", Order = 2 },
                new LookupLanguage { LanguageId = "fr", Name = "French", Order = 2 },
                new LookupLanguage { LanguageId = "ff", Name = "Fulah", Order = 2 },
                new LookupLanguage { LanguageId = "gl", Name = "Galician", Order = 2 },
                new LookupLanguage { LanguageId = "ka", Name = "Georgian", Order = 2 },
                new LookupLanguage { LanguageId = "de", Name = "German", Order = 2 },
                new LookupLanguage { LanguageId = "el", Name = "Greek", Order = 2 },
                new LookupLanguage { LanguageId = "gn", Name = "Guaraní", Order = 2 },
                new LookupLanguage { LanguageId = "gu", Name = "Gujarati", Order = 2 },
                new LookupLanguage { LanguageId = "ht", Name = "Haitian", Order = 2 },
                new LookupLanguage { LanguageId = "ha", Name = "Hausa", Order = 2 },
                new LookupLanguage { LanguageId = "he", Name = "Hebrew", Order = 2 },
                new LookupLanguage { LanguageId = "hz", Name = "Herero", Order = 2 },
                new LookupLanguage { LanguageId = "hi", Name = "Hindi", Order = 2 },
                new LookupLanguage { LanguageId = "ho", Name = "Hiri Motu", Order = 2 },
                new LookupLanguage { LanguageId = "hu", Name = "Hungarian", Order = 2 },
                new LookupLanguage { LanguageId = "ia", Name = "Interlingua", Order = 2 },
                new LookupLanguage { LanguageId = "id", Name = "Indonesian", Order = 2 },
                new LookupLanguage { LanguageId = "ie", Name = "Interlingue", Order = 2 },
                new LookupLanguage { LanguageId = "ga", Name = "Irish", Order = 2 },
                new LookupLanguage { LanguageId = "ig", Name = "Igbo", Order = 2 },
                new LookupLanguage { LanguageId = "ik", Name = "Inupiaq", Order = 2 },
                new LookupLanguage { LanguageId = "is", Name = "Icelandic", Order = 2 },
                new LookupLanguage { LanguageId = "it", Name = "Italian", Order = 2 },
                new LookupLanguage { LanguageId = "iu", Name = "Inuktitut", Order = 2 },
                new LookupLanguage { LanguageId = "ja", Name = "Japanese", Order = 2 },
                new LookupLanguage { LanguageId = "jv", Name = "Javanese", Order = 2 },
                new LookupLanguage { LanguageId = "kl", Name = "Kalaallisut", Order = 2 },
                new LookupLanguage { LanguageId = "kn", Name = "Kannada", Order = 2 },
                new LookupLanguage { LanguageId = "kr", Name = "Kanuri", Order = 2 },
                new LookupLanguage { LanguageId = "ks", Name = "Kashmiri", Order = 2 },
                new LookupLanguage { LanguageId = "kk", Name = "Kazakh", Order = 2 },
                new LookupLanguage { LanguageId = "km", Name = "Khmer", Order = 2 },
                new LookupLanguage { LanguageId = "ki", Name = "Kikuyu", Order = 2 },
                new LookupLanguage { LanguageId = "rw", Name = "Kinyarwanda", Order = 2 },
                new LookupLanguage { LanguageId = "ky", Name = "Kyrgyz", Order = 2 },
                new LookupLanguage { LanguageId = "kv", Name = "Komi", Order = 2 },
                new LookupLanguage { LanguageId = "kg", Name = "Kongo", Order = 2 },
                new LookupLanguage { LanguageId = "ko", Name = "Korean", Order = 2 },
                new LookupLanguage { LanguageId = "ku", Name = "Kurdish", Order = 2 },
                new LookupLanguage { LanguageId = "kj", Name = "Kwanyama", Order = 2 },
                new LookupLanguage { LanguageId = "la", Name = "Latin", Order = 2 },
                new LookupLanguage { LanguageId = "lb", Name = "Luxembourgish", Order = 2 },
                new LookupLanguage { LanguageId = "lg", Name = "Luganda", Order = 2 },
                new LookupLanguage { LanguageId = "li", Name = "Limburgish", Order = 2 },
                new LookupLanguage { LanguageId = "ln", Name = "Lingala", Order = 2 },
                new LookupLanguage { LanguageId = "lo", Name = "Lao", Order = 2 },
                new LookupLanguage { LanguageId = "lt", Name = "Lithuanian", Order = 2 },
                new LookupLanguage { LanguageId = "lu", Name = "Luba-Katanga", Order = 2 },
                new LookupLanguage { LanguageId = "lv", Name = "Latvian", Order = 2 },
                new LookupLanguage { LanguageId = "gv", Name = "Manx", Order = 2 },
                new LookupLanguage { LanguageId = "mk", Name = "Macedonian", Order = 2 },
                new LookupLanguage { LanguageId = "mg", Name = "Malagasy", Order = 2 },
                new LookupLanguage { LanguageId = "ms", Name = "Malay", Order = 2 },
                new LookupLanguage { LanguageId = "ml", Name = "Malayalam", Order = 2 },
                new LookupLanguage { LanguageId = "mt", Name = "Maltese", Order = 2 },
                new LookupLanguage { LanguageId = "mi", Name = "Māori", Order = 2 },
                new LookupLanguage { LanguageId = "mr", Name = "Marathi", Order = 2 },
                new LookupLanguage { LanguageId = "mh", Name = "Marshallese", Order = 2 },
                new LookupLanguage { LanguageId = "mn", Name = "Mongolian", Order = 2 },
                new LookupLanguage { LanguageId = "na", Name = "Nauru", Order = 2 },
                new LookupLanguage { LanguageId = "nv", Name = "Navajo", Order = 2 },
                new LookupLanguage { LanguageId = "nd", Name = "North Ndebele", Order = 2 },
                new LookupLanguage { LanguageId = "ne", Name = "Nepali", Order = 2 },
                new LookupLanguage { LanguageId = "ng", Name = "Ndonga", Order = 2 },
                new LookupLanguage { LanguageId = "nb", Name = "Norwegian Bokmål", Order = 2 },
                new LookupLanguage { LanguageId = "nn", Name = "Norwegian Nynorsk", Order = 2 },
                new LookupLanguage { LanguageId = "no", Name = "Norwegian", Order = 2 },
                new LookupLanguage { LanguageId = "ii", Name = "Nuosu", Order = 2 },
                new LookupLanguage { LanguageId = "nr", Name = "South Ndebele", Order = 2 },
                new LookupLanguage { LanguageId = "oc", Name = "Occitan", Order = 2 },
                new LookupLanguage { LanguageId = "oj", Name = "Ojibwe", Order = 2 },
                new LookupLanguage { LanguageId = "cu", Name = "Old Church Slavonic", Order = 2 },
                new LookupLanguage { LanguageId = "om", Name = "Oromo", Order = 2 },
                new LookupLanguage { LanguageId = "or", Name = "Oriya", Order = 2 },
                new LookupLanguage { LanguageId = "os", Name = "Ossetian", Order = 2 },
                new LookupLanguage { LanguageId = "pa", Name = "Punjabi", Order = 2 },
                new LookupLanguage { LanguageId = "pi", Name = "Pāli", Order = 2 },
                new LookupLanguage { LanguageId = "fa", Name = "Persian", Order = 2 },
                new LookupLanguage { LanguageId = "pl", Name = "Polish", Order = 2 },
                new LookupLanguage { LanguageId = "ps", Name = "Pashto", Order = 2 },
                new LookupLanguage { LanguageId = "pt", Name = "Portuguese", Order = 2 },
                new LookupLanguage { LanguageId = "qu", Name = "Quechua", Order = 2 },
                new LookupLanguage { LanguageId = "rm", Name = "Romansh", Order = 2 },
                new LookupLanguage { LanguageId = "rn", Name = "Kirundi", Order = 2 },
                new LookupLanguage { LanguageId = "ro", Name = "Romanian", Order = 2 },
                new LookupLanguage { LanguageId = "ru", Name = "Russian", Order = 2 },
                new LookupLanguage { LanguageId = "sa", Name = "Sanskrit", Order = 2 },
                new LookupLanguage { LanguageId = "sc", Name = "Sardinian", Order = 2 },
                new LookupLanguage { LanguageId = "sd", Name = "Sindhi", Order = 2 },
                new LookupLanguage { LanguageId = "se", Name = "Northern Sami", Order = 2 },
                new LookupLanguage { LanguageId = "sm", Name = "Samoan", Order = 2 },
                new LookupLanguage { LanguageId = "sg", Name = "Sango", Order = 2 },
                new LookupLanguage { LanguageId = "sr", Name = "Serbian", Order = 2 },
                new LookupLanguage { LanguageId = "gd", Name = "Scottish Gaelic", Order = 2 },
                new LookupLanguage { LanguageId = "sn", Name = "Shona", Order = 2 },
                new LookupLanguage { LanguageId = "si", Name = "Sinhala", Order = 2 },
                new LookupLanguage { LanguageId = "sk", Name = "Slovak", Order = 2 },
                new LookupLanguage { LanguageId = "sl", Name = "Slovene", Order = 2 },
                new LookupLanguage { LanguageId = "so", Name = "Somali", Order = 2 },
                new LookupLanguage { LanguageId = "st", Name = "Southern Sotho", Order = 2 },
                new LookupLanguage { LanguageId = "es", Name = "Spanish", Order = 2 },
                new LookupLanguage { LanguageId = "su", Name = "Sundanese", Order = 2 },
                new LookupLanguage { LanguageId = "sw", Name = "Swahili", Order = 2 },
                new LookupLanguage { LanguageId = "ss", Name = "Swati", Order = 2 },
                new LookupLanguage { LanguageId = "sv", Name = "Swedish", Order = 2 },
                new LookupLanguage { LanguageId = "ta", Name = "Tamil", Order = 2 },
                new LookupLanguage { LanguageId = "te", Name = "Telugu", Order = 2 },
                new LookupLanguage { LanguageId = "tg", Name = "Tajik", Order = 2 },
                new LookupLanguage { LanguageId = "th", Name = "Thai", Order = 2 },
                new LookupLanguage { LanguageId = "ti", Name = "Tigrinya", Order = 2 },
                new LookupLanguage { LanguageId = "bo", Name = "Tibetan", Order = 2 },
                new LookupLanguage { LanguageId = "tk", Name = "Turkmen", Order = 2 },
                new LookupLanguage { LanguageId = "tl", Name = "Tagalog", Order = 2 },
                new LookupLanguage { LanguageId = "tn", Name = "Tswana", Order = 2 },
                new LookupLanguage { LanguageId = "to", Name = "Tonga", Order = 2 },
                new LookupLanguage { LanguageId = "tr", Name = "Turkish", Order = 2 },
                new LookupLanguage { LanguageId = "ts", Name = "Tsonga", Order = 2 },
                new LookupLanguage { LanguageId = "tt", Name = "Tatar", Order = 2 },
                new LookupLanguage { LanguageId = "tw", Name = "Twi", Order = 2 },
                new LookupLanguage { LanguageId = "ty", Name = "Tahitian", Order = 2 },
                new LookupLanguage { LanguageId = "ug", Name = "Uyghur", Order = 2 },
                new LookupLanguage { LanguageId = "uk", Name = "Ukrainian", Order = 2 },
                new LookupLanguage { LanguageId = "ur", Name = "Urdu", Order = 2 },
                new LookupLanguage { LanguageId = "uz", Name = "Uzbek", Order = 2 },
                new LookupLanguage { LanguageId = "ve", Name = "Venda", Order = 2 },
                new LookupLanguage { LanguageId = "vi", Name = "Vietnamese", Order = 2 },
                new LookupLanguage { LanguageId = "vo", Name = "Volapük", Order = 2 },
                new LookupLanguage { LanguageId = "wa", Name = "Walloon", Order = 2 },
                new LookupLanguage { LanguageId = "cy", Name = "Welsh", Order = 2 },
                new LookupLanguage { LanguageId = "wo", Name = "Wolof", Order = 2 },
                new LookupLanguage { LanguageId = "xh", Name = "Xhosa", Order = 2 },
                new LookupLanguage { LanguageId = "yi", Name = "Yiddish", Order = 2 },
                new LookupLanguage { LanguageId = "yo", Name = "Yoruba", Order = 2 },
                new LookupLanguage { LanguageId = "za", Name = "Zhuang", Order = 2 },
                new LookupLanguage { LanguageId = "zu", Name = "Zulu", Order = 2 }
             );


        }
    }
}
