using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VideoLibrary.Data.DbModels;

namespace VideoLibrary.Data.Configuration
{
    internal class LookupCountryConfiguration : IEntityTypeConfiguration<LookupCountry>
    {
        public void Configure(EntityTypeBuilder<LookupCountry> builder)
        {
            builder.ToTable("LookupCountries");

            builder.HasKey(e => e.CountryId);

            builder.Property(e => e.CountryId).IsRequired().HasMaxLength(2);
            builder.Property(e => e.Name).IsRequired().HasMaxLength(50);

            builder.HasData(
                new LookupCountry { CountryId = "AF", Name = "Afghanistan", Order = 2 },
                new LookupCountry { CountryId = "AL", Name = "Albania", Order = 2 },
                new LookupCountry { CountryId = "DZ", Name = "Algeria", Order = 2 },
                new LookupCountry { CountryId = "AS", Name = "American Samoa", Order = 2 },
                new LookupCountry { CountryId = "AD", Name = "Andorra", Order = 2 },
                new LookupCountry { CountryId = "AO", Name = "Angola", Order = 2 },
                new LookupCountry { CountryId = "AG", Name = "Antigua and Barbuda", Order = 2 },
                new LookupCountry { CountryId = "AR", Name = "Argentina", Order = 2 },
                new LookupCountry { CountryId = "AM", Name = "Armenia", Order = 2 },
                new LookupCountry { CountryId = "AU", Name = "Australia", Order = 2 },
                new LookupCountry { CountryId = "AT", Name = "Austria", Order = 2 },
                new LookupCountry { CountryId = "AZ", Name = "Azerbaijan", Order = 2 },
                new LookupCountry { CountryId = "BS", Name = "Bahamas", Order = 2 },
                new LookupCountry { CountryId = "BH", Name = "Bahrain", Order = 2 },
                new LookupCountry { CountryId = "BD", Name = "Bangladesh", Order = 2 },
                new LookupCountry { CountryId = "BB", Name = "Barbados", Order = 2 },
                new LookupCountry { CountryId = "BY", Name = "Belarus", Order = 2 },
                new LookupCountry { CountryId = "BE", Name = "Belgium", Order = 2 },
                new LookupCountry { CountryId = "BZ", Name = "Belize", Order = 2 },
                new LookupCountry { CountryId = "BJ", Name = "Benin", Order = 2 },
                new LookupCountry { CountryId = "BT", Name = "Bhutan", Order = 2 },
                new LookupCountry { CountryId = "BO", Name = "Bolivia", Order = 2 },
                new LookupCountry { CountryId = "BA", Name = "Bosnia and Herzegovina", Order = 2 },
                new LookupCountry { CountryId = "BW", Name = "Botswana", Order = 2 },
                new LookupCountry { CountryId = "BR", Name = "Brazil", Order = 2 },
                new LookupCountry { CountryId = "BN", Name = "Brunei", Order = 2 },
                new LookupCountry { CountryId = "BG", Name = "Bulgaria", Order = 2 },
                new LookupCountry { CountryId = "BF", Name = "Burkina Faso", Order = 2 },
                new LookupCountry { CountryId = "BI", Name = "Burundi", Order = 2 },
                new LookupCountry { CountryId = "KH", Name = "Cambodia", Order = 2 },
                new LookupCountry { CountryId = "CM", Name = "Cameroon", Order = 2 },
                new LookupCountry { CountryId = "CA", Name = "Canada", Order = 0 },
                new LookupCountry { CountryId = "CV", Name = "Cape Verde", Order = 2 },
                new LookupCountry { CountryId = "CF", Name = "Central African Republic", Order = 2 },
                new LookupCountry { CountryId = "TD", Name = "Chad", Order = 2 },
                new LookupCountry { CountryId = "CL", Name = "Chile", Order = 2 },
                new LookupCountry { CountryId = "CN", Name = "China", Order = 2 },
                new LookupCountry { CountryId = "CO", Name = "Colombia", Order = 2 },
                new LookupCountry { CountryId = "KM", Name = "Comoros", Order = 2 },
                new LookupCountry { CountryId = "CG", Name = "Congo (Brazzaville)", Order = 2 },
                new LookupCountry { CountryId = "CD", Name = "Congo (Kinshasa)", Order = 2 },
                new LookupCountry { CountryId = "CR", Name = "Costa Rica", Order = 2 },
                new LookupCountry { CountryId = "HR", Name = "Croatia", Order = 2 },
                new LookupCountry { CountryId = "CU", Name = "Cuba", Order = 2 },
                new LookupCountry { CountryId = "CY", Name = "Cyprus", Order = 2 },
                new LookupCountry { CountryId = "CZ", Name = "Czech Republic", Order = 2 },
                new LookupCountry { CountryId = "DK", Name = "Denmark", Order = 2 },
                new LookupCountry { CountryId = "DJ", Name = "Djibouti", Order = 2 },
                new LookupCountry { CountryId = "DM", Name = "Dominica", Order = 2 },
                new LookupCountry { CountryId = "DO", Name = "Dominican Republic", Order = 2 },
                new LookupCountry { CountryId = "EC", Name = "Ecuador", Order = 2 },
                new LookupCountry { CountryId = "EG", Name = "Egypt", Order = 2 },
                new LookupCountry { CountryId = "SV", Name = "El Salvador", Order = 2 },
                new LookupCountry { CountryId = "GQ", Name = "Equatorial Guinea", Order = 2 },
                new LookupCountry { CountryId = "ER", Name = "Eritrea", Order = 2 },
                new LookupCountry { CountryId = "EE", Name = "Estonia", Order = 2 },
                new LookupCountry { CountryId = "ET", Name = "Ethiopia", Order = 2 },
                new LookupCountry { CountryId = "FJ", Name = "Fiji", Order = 2 },
                new LookupCountry { CountryId = "FI", Name = "Finland", Order = 2 },
                new LookupCountry { CountryId = "FR", Name = "France", Order = 2 },
                new LookupCountry { CountryId = "GA", Name = "Gabon", Order = 2 },
                new LookupCountry { CountryId = "GM", Name = "Gambia", Order = 2 },
                new LookupCountry { CountryId = "GE", Name = "Georgia", Order = 2 },
                new LookupCountry { CountryId = "DE", Name = "Germany", Order = 2 },
                new LookupCountry { CountryId = "GH", Name = "Ghana", Order = 2 },
                new LookupCountry { CountryId = "GR", Name = "Greece", Order = 2 },
                new LookupCountry { CountryId = "GD", Name = "Grenada", Order = 2 },
                new LookupCountry { CountryId = "GT", Name = "Guatemala", Order = 2 },
                new LookupCountry { CountryId = "GN", Name = "Guinea", Order = 2 },
                new LookupCountry { CountryId = "GW", Name = "Guinea-Bissau", Order = 2 },
                new LookupCountry { CountryId = "GY", Name = "Guyana", Order = 2 },
                new LookupCountry { CountryId = "HT", Name = "Haiti", Order = 2 },
                new LookupCountry { CountryId = "HN", Name = "Honduras", Order = 2 },
                new LookupCountry { CountryId = "HU", Name = "Hungary", Order = 2 },
                new LookupCountry { CountryId = "IS", Name = "Iceland", Order = 2 },
                new LookupCountry { CountryId = "IN", Name = "India", Order = 2 },
                new LookupCountry { CountryId = "ID", Name = "Indonesia", Order = 2 },
                new LookupCountry { CountryId = "IR", Name = "Iran", Order = 2 },
                new LookupCountry { CountryId = "IQ", Name = "Iraq", Order = 2 },
                new LookupCountry { CountryId = "IE", Name = "Ireland", Order = 2 },
                new LookupCountry { CountryId = "IL", Name = "Israel", Order = 2 },
                new LookupCountry { CountryId = "IT", Name = "Italy", Order = 2 },
                new LookupCountry { CountryId = "JM", Name = "Jamaica", Order = 2 },
                new LookupCountry { CountryId = "JP", Name = "Japan", Order = 2 },
                new LookupCountry { CountryId = "JO", Name = "Jordan", Order = 2 },
                new LookupCountry { CountryId = "KZ", Name = "Kazakhstan", Order = 2 },
                new LookupCountry { CountryId = "KE", Name = "Kenya", Order = 2 },
                new LookupCountry { CountryId = "KI", Name = "Kiribati", Order = 2 },
                new LookupCountry { CountryId = "KR", Name = "South Korea", Order = 2 },
                new LookupCountry { CountryId = "KW", Name = "Kuwait", Order = 2 },
                new LookupCountry { CountryId = "KG", Name = "Kyrgyzstan", Order = 2 },
                new LookupCountry { CountryId = "LA", Name = "Laos", Order = 2 },
                new LookupCountry { CountryId = "LV", Name = "Latvia", Order = 2 },
                new LookupCountry { CountryId = "LB", Name = "Lebanon", Order = 2 },
                new LookupCountry { CountryId = "LS", Name = "Lesotho", Order = 2 },
                new LookupCountry { CountryId = "LR", Name = "Liberia", Order = 2 },
                new LookupCountry { CountryId = "LY", Name = "Libya", Order = 2 },
                new LookupCountry { CountryId = "LI", Name = "Liechtenstein", Order = 2 },
                new LookupCountry { CountryId = "LT", Name = "Lithuania", Order = 2 },
                new LookupCountry { CountryId = "LU", Name = "Luxembourg", Order = 2 },
                new LookupCountry { CountryId = "MG", Name = "Madagascar", Order = 2 },
                new LookupCountry { CountryId = "MW", Name = "Malawi", Order = 2 },
                new LookupCountry { CountryId = "MY", Name = "Malaysia", Order = 2 },
                new LookupCountry { CountryId = "MV", Name = "Maldives", Order = 2 },
                new LookupCountry { CountryId = "ML", Name = "Mali", Order = 2 },
                new LookupCountry { CountryId = "MT", Name = "Malta", Order = 2 },
                new LookupCountry { CountryId = "MH", Name = "Marshall Islands", Order = 2 },
                new LookupCountry { CountryId = "MR", Name = "Mauritania", Order = 2 },
                new LookupCountry { CountryId = "MU", Name = "Mauritius", Order = 2 },
                new LookupCountry { CountryId = "MX", Name = "Mexico", Order = 2 },
                new LookupCountry { CountryId = "FM", Name = "Micronesia", Order = 2 },
                new LookupCountry { CountryId = "MD", Name = "Moldova", Order = 2 },
                new LookupCountry { CountryId = "MC", Name = "Monaco", Order = 2 },
                new LookupCountry { CountryId = "MN", Name = "Mongolia", Order = 2 },
                new LookupCountry { CountryId = "ME", Name = "Montenegro", Order = 2 },
                new LookupCountry { CountryId = "MA", Name = "Morocco", Order = 2 },
                new LookupCountry { CountryId = "MZ", Name = "Mozambique", Order = 2 },
                new LookupCountry { CountryId = "MM", Name = "Myanmar (Burma)", Order = 2 },
                new LookupCountry { CountryId = "NA", Name = "Namibia", Order = 2 },
                new LookupCountry { CountryId = "NR", Name = "Nauru", Order = 2 },
                new LookupCountry { CountryId = "NP", Name = "Nepal", Order = 2 },
                new LookupCountry { CountryId = "NL", Name = "Netherlands", Order = 2 },
                new LookupCountry { CountryId = "NZ", Name = "New Zealand", Order = 2 },
                new LookupCountry { CountryId = "NI", Name = "Nicaragua", Order = 2 },
                new LookupCountry { CountryId = "NE", Name = "Niger", Order = 2 },
                new LookupCountry { CountryId = "NG", Name = "Nigeria", Order = 2 },
                new LookupCountry { CountryId = "NO", Name = "Norway", Order = 2 },
                new LookupCountry { CountryId = "OM", Name = "Oman", Order = 2 },
                new LookupCountry { CountryId = "PK", Name = "Pakistan", Order = 2 },
                new LookupCountry { CountryId = "PW", Name = "Palau", Order = 2 },
                new LookupCountry { CountryId = "PS", Name = "Palestine", Order = 2 },
                new LookupCountry { CountryId = "PA", Name = "Panama", Order = 2 },
                new LookupCountry { CountryId = "PG", Name = "Papua New Guinea", Order = 2 },
                new LookupCountry { CountryId = "PY", Name = "Paraguay", Order = 2 },
                new LookupCountry { CountryId = "PE", Name = "Peru", Order = 2 },
                new LookupCountry { CountryId = "PH", Name = "Philippines", Order = 2 },
                new LookupCountry { CountryId = "PL", Name = "Poland", Order = 2 },
                new LookupCountry { CountryId = "PT", Name = "Portugal", Order = 2 },
                new LookupCountry { CountryId = "QA", Name = "Qatar", Order = 2 },
                new LookupCountry { CountryId = "RO", Name = "Romania", Order = 2 },
                new LookupCountry { CountryId = "RU", Name = "Russia", Order = 2 },
                new LookupCountry { CountryId = "RW", Name = "Rwanda", Order = 2 },
                new LookupCountry { CountryId = "KN", Name = "Saint Kitts and Nevis", Order = 2 },
                new LookupCountry { CountryId = "LC", Name = "Saint Lucia", Order = 2 },
                new LookupCountry { CountryId = "VC", Name = "Saint Vincent and Grenadines", Order = 2 },
                new LookupCountry { CountryId = "WS", Name = "Samoa", Order = 2 },
                new LookupCountry { CountryId = "SM", Name = "San Marino", Order = 2 },
                new LookupCountry { CountryId = "ST", Name = "São Tomé and Príncipe", Order = 2 },
                new LookupCountry { CountryId = "SA", Name = "Saudi Arabia", Order = 2 },
                new LookupCountry { CountryId = "SN", Name = "Senegal", Order = 2 },
                new LookupCountry { CountryId = "RS", Name = "Serbia", Order = 2 },
                new LookupCountry { CountryId = "SC", Name = "Seychelles", Order = 2 },
                new LookupCountry { CountryId = "SL", Name = "Sierra Leone", Order = 2 },
                new LookupCountry { CountryId = "SG", Name = "Singapore", Order = 2 },
                new LookupCountry { CountryId = "SK", Name = "Slovakia", Order = 2 },
                new LookupCountry { CountryId = "SI", Name = "Slovenia", Order = 2 },
                new LookupCountry { CountryId = "SB", Name = "Solomon Islands", Order = 2 },
                new LookupCountry { CountryId = "SO", Name = "Somalia", Order = 2 },
                new LookupCountry { CountryId = "ZA", Name = "South Africa", Order = 2 },
                new LookupCountry { CountryId = "SS", Name = "South Sudan", Order = 2 },
                new LookupCountry { CountryId = "ES", Name = "Spain", Order = 2 },
                new LookupCountry { CountryId = "LK", Name = "Sri Lanka", Order = 2 },
                new LookupCountry { CountryId = "SD", Name = "Sudan", Order = 2 },
                new LookupCountry { CountryId = "SR", Name = "Suriname", Order = 2 },
                new LookupCountry { CountryId = "SZ", Name = "Swaziland (Eswatini)", Order = 2 },
                new LookupCountry { CountryId = "SE", Name = "Sweden", Order = 2 },
                new LookupCountry { CountryId = "CH", Name = "Switzerland", Order = 2 },
                new LookupCountry { CountryId = "SY", Name = "Syria", Order = 2 },
                new LookupCountry { CountryId = "TW", Name = "Taiwan", Order = 2 },
                new LookupCountry { CountryId = "TJ", Name = "Tajikistan", Order = 2 },
                new LookupCountry { CountryId = "TZ", Name = "Tanzania", Order = 2 },
                new LookupCountry { CountryId = "TH", Name = "Thailand", Order = 2 },
                new LookupCountry { CountryId = "TL", Name = "Timor-Leste", Order = 2 },
                new LookupCountry { CountryId = "TG", Name = "Togo", Order = 2 },
                new LookupCountry { CountryId = "TO", Name = "Tonga", Order = 2 },
                new LookupCountry { CountryId = "TT", Name = "Trinidad and Tobago", Order = 2 },
                new LookupCountry { CountryId = "TN", Name = "Tunisia", Order = 2 },
                new LookupCountry { CountryId = "TR", Name = "Turkey", Order = 2 },
                new LookupCountry { CountryId = "TM", Name = "Turkmenistan", Order = 2 },
                new LookupCountry { CountryId = "TV", Name = "Tuvalu", Order = 2 },
                new LookupCountry { CountryId = "UG", Name = "Uganda", Order = 2 },
                new LookupCountry { CountryId = "UA", Name = "Ukraine", Order = 2 },
                new LookupCountry { CountryId = "AE", Name = "United Arab Emirates", Order = 2 },
                new LookupCountry { CountryId = "GB", Name = "United Kingdom", Order = 2 },
                new LookupCountry { CountryId = "US", Name = "United States", Order = 1 },
                new LookupCountry { CountryId = "UY", Name = "Uruguay", Order = 2 },
                new LookupCountry { CountryId = "UZ", Name = "Uzbekistan", Order = 2 },
                new LookupCountry { CountryId = "VU", Name = "Vanuatu", Order = 2 },
                new LookupCountry { CountryId = "VE", Name = "Venezuela", Order = 2 },
                new LookupCountry { CountryId = "VN", Name = "Vietnam", Order = 2 },
                new LookupCountry { CountryId = "YE", Name = "Yemen", Order = 2 },
                new LookupCountry { CountryId = "ZM", Name = "Zambia", Order = 2 },
                new LookupCountry { CountryId = "ZW", Name = "Zimbabwe", Order = 2 }
             );
        }
    }
}
