@Host = {{HostAddress}}
 
GET {{Host}}/Countries
Accept: application/json
 
###

GET {{Host}}/Genres
Accept: application/json
 
###

GET {{Host}}/Languages
Accept: application/json
 
###

GET {{Host}}/Ratings
Accept: application/json
 
###

 
